#requires -Version 7.2
<#
.SYNOPSIS
    Tests, publishes and deploys only the .NET native Activity finance agent.
.DESCRIPTION
    Uses the existing pinned Activity SDK feed/cache; never rebuilds or upgrades it.
    Publishes a framework-dependent linux-x64 bundle for local validation.
    AZD bundled packaging independently publishes the host project from azure.yaml.
    PublishOnly runs local tests (excluding live routing evaluations) and stages
    the validation bundle without reading or changing Azure/azd state.
    An existing ONE_SESSION_KEY_SALT is never rotated. Channel configuration uses
    only the selected bot's mcs connection or explicitly supplied OAuth settings.
#>
[CmdletBinding(DefaultParameterSetName = 'Deploy')]
param(
    [Parameter(ParameterSetName = 'Deploy')] [string] $EnvironmentName = 'zavafinance',
    [Parameter(Mandatory, ParameterSetName = 'Deploy')] [string] $SearchResourceId,
    [Parameter(ParameterSetName = 'Deploy')] [Alias('TokenExchangeResource')] [string] $UserAuthResource,
    [Parameter(ParameterSetName = 'Deploy')] [string] $DelegatedScopes,
    [Parameter(Mandatory, ParameterSetName = 'Publish')] [switch] $PublishOnly,
    [switch] $NoRestore
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$hostProject = Join-Path $root 'src\dotnet\ZavaFinance.One.Host\ZavaFinance.One.Host.csproj'
$tests = Join-Path $root 'src\dotnet\tests\ZavaFinance.Tests\ZavaFinance.Tests.csproj'
$package = Join-Path $root '.artifacts\one-sdk\feed\Azure.AI.AgentServer.Activity.1.0.0-beta.1.source.dc9cca2d1f1c.core28.m3651877.nupkg'
$publish = Join-Path $root '.artifacts\dotnet-agent'
if (-not (Test-Path -LiteralPath $package -PathType Leaf)) {
    throw 'Restore the pinned Activity SDK feed under .artifacts\one-sdk\feed first; see scripts\build-experimental-activity-sdk.ps1.'
}

$restoreArguments = @(if ($NoRestore) { '--no-restore' })
& dotnet test $tests --configuration Release --filter 'FullyQualifiedName!~RoutingEvalTests' @restoreArguments
if ($LASTEXITCODE -ne 0) { throw '.NET tests failed; publishing and deployment stopped.' }

# Only this marked, generated deployment directory is cleaned; SDK/cache state is untouched.
$marker = Join-Path $publish '.zavafinance-publish'
if (Test-Path -LiteralPath $publish) {
    if (-not (Test-Path -LiteralPath $marker -PathType Leaf)) {
        throw 'Refusing to overwrite an unmarked .artifacts\dotnet-agent directory.'
    }
    $items = @(Get-ChildItem -LiteralPath $publish -Force -Recurse)
    if ((Get-Item -LiteralPath $publish).Attributes.HasFlag([IO.FileAttributes]::ReparsePoint) `
        -or @($items | Where-Object { $_.Attributes.HasFlag([IO.FileAttributes]::ReparsePoint) }).Count) {
        throw 'Refusing to clean a deployment directory containing links.'
    }
    foreach ($file in $items | Where-Object { -not $_.PSIsContainer }) {
        Remove-Item -LiteralPath $file.FullName -Force
    }
    foreach ($directory in $items | Where-Object PSIsContainer | Sort-Object { $_.FullName.Length } -Descending) {
        [IO.Directory]::Delete($directory.FullName)
    }
}
else {
    New-Item -ItemType Directory -Path $publish | Out-Null
}
Set-Content -LiteralPath $marker -Value 'Generated by scripts\deploy-dotnet.ps1'
& dotnet publish $hostProject --configuration Release --runtime linux-x64 --self-contained false `
    --output $publish @restoreArguments
if ($LASTEXITCODE -ne 0) { throw '.NET linux-x64 publish failed; deployment stopped.' }
foreach ($file in @('ZavaFinance.One.Host.dll', 'ZavaFinance.One.Host.deps.json', 'ZavaFinance.One.Host.runtimeconfig.json',
    'ZavaFinance.One.dll', 'ZavaFinance.Agent.dll', 'Azure.AI.AgentServer.Activity.dll')) {
    if (-not (Test-Path -LiteralPath (Join-Path $publish $file) -PathType Leaf)) {
        throw "Incomplete bundled publish: missing $file."
    }
}
# These rules protect manual use of the validation bundle; AZD publishes the host independently.
$ignore = @('.zavafinance-publish', '*.pdb', '*.zip', '*.azd-generated', '.env', '.env.*',
    'appsettings.Development.json', 'appsettings.Local.json', '*.pfx', '*.pem', '*.key')
Set-Content -LiteralPath (Join-Path $publish '.agentignore') -Value $ignore
Set-Content -LiteralPath (Join-Path $publish '.azdignore') -Value $ignore
Write-Host "Bundled .NET validation output staged: $publish"
if ($PublishOnly) { return }

. (Join-Path $PSScriptRoot 'Agent-Deployment.ps1')
Initialize-AgentEnvironment -Root $root -EnvironmentName $EnvironmentName -Prefix ONE
& azd deploy zavafinance-one --environment $EnvironmentName --cwd $root --no-prompt
if ($LASTEXITCODE -ne 0) { throw '.NET hosted-agent deployment failed.' }
$channel = @{ Variant = 'DotNet'; EnvironmentName = $EnvironmentName; SearchResourceId = $SearchResourceId }
foreach ($name in @('UserAuthResource', 'DelegatedScopes')) {
    if ($PSBoundParameters.ContainsKey($name)) { $channel[$name] = $PSBoundParameters[$name] }
}
& (Join-Path $PSScriptRoot 'configure-channel.ps1') @channel
Write-Host '.NET agent deployed and its channel configured. Interactive acceptance remains a separate step.'
